'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import GoogleJobSearchResults, { type SiteQuery } from '../components/GoogleJobSearchResults';
import ProfessionalProfileSelect from '../components/ProfessionalProfileSelect';
import { fetchKall } from '../lib/api';
import styles from './ConsultingTab.module.css';

type Lead = { id: number; organization: string; opportunity_name: string; relationship_segment: string; source: string | null; service_line: string | null; stage: string; projected_value_cents: number | null; next_step: string | null };
type Proposal = { id: number; lead_id: number; title: string; summary: string | null; scope: string | null; deliverables: string[]; fee_cents: number | null; status: string };
type FollowUp = { id: number; lead_id: number; due_on: string; channel: string; purpose: string; draft_message: string | null; status: string };
type Engagement = { id: number; lead_id: number | null; client_name: string; name: string; status: string; fee_cents: number | null; design_partner_product: string | null; design_partner_stage: string | null };
type Practice = { available: boolean; engagement_types: string[]; rate_cents: number | null; rate_basis: string; currency: string; availability_note: string | null; agreement_url: string | null };
type Workspace = { leads: Lead[]; proposals: Proposal[]; follow_ups: FollowUp[]; engagements: Engagement[]; practice: Practice | null; career_page: { exists: boolean; published: boolean; slug: string | null } };
type DiscoveryPlan = {
  positioning: string;
  qualification_questions: string[];
  searches: Array<{ provider: string; query: string; rationale: string }>;
  search_enabled: boolean;
  results: Array<{ title: string; url: string; snippet: string; provider: string; suggested_segment: string }>;
  warm_lead_prompts: Array<{ contact_id: number; name: string; company: string | null; assistant_prompt: string }>;
};
type Submit = (path: string, body: object, success: string, method?: string) => Promise<boolean>;

const EMPTY_WORKSPACE: Workspace = { leads: [], proposals: [], follow_ups: [], engagements: [], practice: null, career_page: { exists: false, published: false, slug: null } };
const WARM_SEGMENTS = new Set(['warm_contact', 'former_colleague', 'past_client', 'referral', 'community']);
const SEGMENTS = [
  ['warm_contact', 'Warm contact'], ['former_colleague', 'Former colleague'], ['past_client', 'Past client'], ['referral', 'Referral'],
  ['community', 'Community'], ['inbound', 'Inbound'], ['marketplace', 'Marketplace'], ['cold', 'Cold prospect'],
] as const;
const CHANNELS = [
  { name: 'Catalant', url: 'https://catalant.com/for-independent-consultants/', note: 'Independent specialists and project-based consulting.' },
  { name: 'Business Talent Group', url: 'https://talent.businesstalentgroup.com/', note: 'Independent professionals, operators, and interim leaders.' },
  { name: 'Contra', url: 'https://contra.com/', note: 'Portfolio-led independent work across creative, commercial, and technical fields.' },
  { name: 'Upwork', url: 'https://www.upwork.com/', note: 'Broad project work spanning business, creative, service, and technical fields.' },
] as const;
function money(cents: number | null) { return cents === null ? 'Value not set' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(cents / 100); }
function label(value: string) { return value.replaceAll('_', ' '); }
async function responseMessage(response: Response, fallback: string) { try { const body = await response.json(); return typeof body?.detail === 'string' ? body.detail : fallback; } catch { return fallback; } }

export default function ConsultingTab() {
  const [workspace, setWorkspace] = useState<Workspace>(EMPTY_WORKSPACE);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  const [segment, setSegment] = useState('all');
  const [activeForm, setActiveForm] = useState<'lead' | 'proposal' | 'follow-up' | 'engagement' | null>(null);
  const [selectedLeadId, setSelectedLeadId] = useState('');
  const [profileId, setProfileId] = useState('');
  const [extraTerms, setExtraTerms] = useState('');
  const [queries, setQueries] = useState<SiteQuery[]>([]);
  const [discoveryPlan, setDiscoveryPlan] = useState<DiscoveryPlan | null>(null);
  const visibleLeads = useMemo(() => workspace.leads.filter((lead) => segment === 'all' || (segment === 'warm' ? WARM_SEGMENTS.has(lead.relationship_segment) : lead.relationship_segment === segment)), [segment, workspace.leads]);
  const leadNames = useMemo(() => new Map(workspace.leads.map((lead) => [lead.id, `${lead.organization}: ${lead.opportunity_name}`])), [workspace.leads]);
  const vaettirPartners = workspace.engagements.filter((engagement) => engagement.design_partner_product === 'vaettir');

  async function loadWorkspace(signal?: AbortSignal) {
    const response = await fetchKall('/me/consulting/workspace', { signal });
    if (!response.ok) throw new Error(await responseMessage(response, 'Unable to load the consulting workspace.'));
    setWorkspace(await response.json());
  }
  useEffect(() => {
    const controller = new AbortController();
    loadWorkspace(controller.signal).catch((error) => { if (error.name !== 'AbortError') setMessage(error.message); }).finally(() => setLoading(false));
    return () => controller.abort();
  }, []);
  async function submit(path: string, body: object, success: string, method = 'POST') {
    setMessage('Saving…');
    const response = await fetchKall(path, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    if (!response.ok) { setMessage(await responseMessage(response, 'Kall could not save that change.')); return false; }
    await loadWorkspace(); setMessage(success); return true;
  }
  function chooseForm(form: typeof activeForm, leadId?: number) {
    setSelectedLeadId(leadId ? String(leadId) : selectedLeadId || String(workspace.leads[0]?.id || ''));
    setActiveForm(form);
    window.setTimeout(() => document.getElementById('consulting-editor')?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 0);
  }
  async function prepareLeadSearch(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!profileId) { setMessage('Choose a professional profile so Kall can tailor the consulting search.'); return; }
    setMessage('Kall is preparing lead paths…');
    const query = extraTerms.trim() ? `?focus=${encodeURIComponent(extraTerms.trim())}` : '';
    const response = await fetchKall(`/me/consulting/discovery-plan/${profileId}${query}`);
    if (!response.ok) { setMessage(await responseMessage(response, 'Unable to prepare consulting searches.')); return; }
    const plan: DiscoveryPlan = await response.json();
    setDiscoveryPlan(plan);
    // The server already ran the searches; the per-site widget is only the
    // fallback when no search key is configured.
    setQueries(plan.search_enabled ? [] : plan.searches.map((item) => ({ provider: item.provider, domain: '', query: item.query })));
    setMessage(plan.results.length
      ? `Found ${plan.results.length} public ${plan.results.length === 1 ? 'opening' : 'openings'} for this direction.`
      : 'Kall prepared public searches and qualification questions for this direction.');
  }

  async function savePractice(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const engagementTypes = data.getAll('engagement_types').map(String);
    await submit('/me/consulting/practice', {
      available: data.get('available') === 'on',
      engagement_types: engagementTypes,
      rate_cents: data.get('rate') ? Math.round(Number(data.get('rate')) * 100) : null,
      rate_basis: data.get('rate_basis'),
      currency: 'USD',
      availability_note: data.get('availability_note') || null,
      agreement_url: data.get('agreement_url') || null,
    }, 'Consulting offer saved.', 'PUT');
  }

  return <section aria-label="Consulting opportunities" className={styles.workspace}>
    <section className="card"><span className="eyebrow">Consulting pipeline</span><div className={styles.heroRow}><div><h2>Turn trusted relationships into reviewable consulting work.</h2><p>Track a prospect, prepare a proposal, and plan each follow-up. Kall stores drafts and approvals but never contacts anyone or submits on your behalf.</p></div><button className="button" type="button" onClick={() => chooseForm('lead')}>Add a lead</button></div><div className={styles.metrics} aria-label="Consulting pipeline summary"><div><strong>{workspace.leads.length}</strong><span>leads</span></div><div><strong>{workspace.follow_ups.filter((item) => item.status !== 'completed').length}</strong><span>follow-ups</span></div><div><strong>{workspace.engagements.filter((item) => item.status === 'active').length}</strong><span>active engagements</span></div><div><strong>{vaettirPartners.length}</strong><span>Vaettir partners</span></div></div></section>
    <p className={styles.status} role="status" aria-live="polite">{loading ? 'Loading your consulting workspace…' : message}</p>

    <section className="card" aria-labelledby="practice-heading"><div className={styles.cardTop}><div><span className="eyebrow">Your consulting offer</span><h2 id="practice-heading" style={{ marginTop: 14 }}>Set expectations before looking for leads.</h2></div><a className="button secondary" href="/settings/career-page">{workspace.career_page.exists ? 'Edit shareable portfolio' : 'Create shareable portfolio first'}</a></div><p>Your public portfolio only shows this offer and rate when you explicitly mark yourself available below.</p><form key={JSON.stringify(workspace.practice)} className="form" onSubmit={(event) => void savePractice(event)}><label className={styles.check}><input name="available" type="checkbox" defaultChecked={workspace.practice?.available ?? false} /> I am available for consulting or fractional work</label><fieldset><legend>Engagement types</legend><div className={styles.actions}>{[['consulting','Consulting'],['fractional','Fractional role'],['advisory','Advisory'],['project','Fixed project']].map(([value,text]) => <label className={styles.check} key={value}><input name="engagement_types" value={value} type="checkbox" defaultChecked={workspace.practice?.engagement_types.includes(value) ?? false} /> {text}</label>)}</div></fieldset><div className="two"><label><span className="muted">Consulting rate (USD)</span><input className="input" name="rate" type="number" min="0" step="1" defaultValue={workspace.practice?.rate_cents == null ? '' : workspace.practice.rate_cents / 100} /></label><label><span className="muted">Rate basis</span><select className="input" name="rate_basis" defaultValue={workspace.practice?.rate_basis ?? 'hour'}><option value="hour">Per hour</option><option value="day">Per day</option><option value="project">Starting per project</option><option value="month">Per month</option></select></label></div><label><span className="muted">Availability</span><input className="input" name="availability_note" defaultValue={workspace.practice?.availability_note ?? ''} placeholder="e.g. Available for one fractional engagement starting October" /></label><label><span className="muted">Agreement or engagement terms link</span><input className="input" name="agreement_url" type="url" defaultValue={workspace.practice?.agreement_url ?? ''} placeholder="https://…" /></label><button className="button" type="submit">Save consulting offer</button></form>{workspace.career_page.published && workspace.career_page.slug ? <p><a href={`/p/${workspace.career_page.slug}`} target="_blank">View the public portfolio</a></p> : <p className={styles.boundary}>Your portfolio is not public yet. Review and publish it when ready.</p>}</section>

    <section aria-labelledby="lead-heading"><div className="section-heading"><div><span className="eyebrow">Lead workspace</span><h2 id="lead-heading">Know where each conversation stands.</h2></div><label className={styles.filter}>Relationship <select className="input" value={segment} onChange={(event) => setSegment(event.target.value)}><option value="all">All leads</option><option value="warm">All warm relationships</option>{SEGMENTS.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label></div><div className={styles.cardGrid}>{visibleLeads.map((lead) => <article className="card" key={lead.id}><div className={styles.cardTop}><span className="pill">{label(lead.stage)}</span><span className={styles.value}>{money(lead.projected_value_cents)}</span></div><h3 className={styles.cardTitle}>{lead.opportunity_name}</h3><p>{lead.organization} · {label(lead.relationship_segment)}</p>{lead.next_step && <p className={styles.nextStep}><strong>Next:</strong> {lead.next_step}</p>}<label className={styles.compactLabel}>Stage <select className="input" value={lead.stage} onChange={(event) => void submit(`/me/consulting/leads/${lead.id}`, { stage: event.target.value }, 'Lead stage updated.', 'PATCH')}><option value="identified">Identified</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option><option value="negotiation">Negotiation</option><option value="won">Won</option><option value="lost">Lost</option><option value="paused">Paused</option></select></label><div className={styles.actions}><button className="button secondary" type="button" onClick={() => chooseForm('proposal', lead.id)}>Proposal</button><button className="button secondary" type="button" onClick={() => chooseForm('follow-up', lead.id)}>Follow-up</button><button className="button ghost" type="button" onClick={() => chooseForm('engagement', lead.id)}>Engagement</button></div></article>)}{!loading && visibleLeads.length === 0 && <article className="card"><h3>No leads in this segment</h3><p>Add a prospect or change the relationship filter.</p></article>}</div></section>

    {activeForm && <Editor form={activeForm} leads={workspace.leads} selectedLeadId={selectedLeadId} setSelectedLeadId={setSelectedLeadId} submit={submit} close={() => setActiveForm(null)} />}

    <section aria-labelledby="follow-up-heading"><div className="section-heading"><div><span className="eyebrow">Follow-up queue</span><h2 id="follow-up-heading">Review every message before it leaves Kall.</h2></div>{workspace.leads.length > 0 && <button className="button secondary" type="button" onClick={() => chooseForm('follow-up')}>Queue follow-up</button>}</div><div className={styles.cardGrid}>{workspace.follow_ups.map((item) => <FollowUpCard key={item.id} item={item} leadName={leadNames.get(item.lead_id)} submit={submit} />)}{!loading && workspace.follow_ups.length === 0 && <article className="card"><h3>Your queue is clear</h3><p>Create a follow-up from a lead when there is a real next conversation to plan.</p></article>}</div></section>

    <section aria-labelledby="proposal-heading"><div className="section-heading"><div><span className="eyebrow">Proposal drafts</span><h2 id="proposal-heading">Define the work before sharing it.</h2></div>{workspace.leads.length > 0 && <button className="button secondary" type="button" onClick={() => chooseForm('proposal')}>Draft proposal</button>}</div><div className={styles.cardGrid}>{workspace.proposals.map((item) => <ProposalCard key={item.id} item={item} leadName={leadNames.get(item.lead_id)} submit={submit} />)}{!loading && workspace.proposals.length === 0 && <article className="card"><h3>No proposals yet</h3><p>Start with a qualified lead, then write a scope and deliverables that can be reviewed.</p></article>}</div></section>

    <section aria-labelledby="engagement-heading"><div className="section-heading"><div><span className="eyebrow">Engagements</span><h2 id="engagement-heading">Track active client work and paid design partners.</h2></div><button className="button secondary" type="button" onClick={() => chooseForm('engagement')}>Add engagement</button></div><div className={styles.cardGrid}>{workspace.engagements.map((item) => <article className="card" key={item.id}><div className={styles.cardTop}><span className="pill">{label(item.status)}</span><span className={styles.value}>{money(item.fee_cents)}</span></div><h3 className={styles.cardTitle}>{item.name}</h3><p>{item.client_name}</p><label className={styles.compactLabel}>Engagement status <select className="input" value={item.status} onChange={(event) => void submit(`/me/consulting/engagements/${item.id}`, { status: event.target.value }, 'Engagement status updated.', 'PATCH')}><option value="planned">Planned</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>{item.design_partner_product === 'vaettir' && <><p className={styles.partner}>Vaettir paid design partner · {label(item.design_partner_stage || 'discovery')}</p><label className={styles.compactLabel}>Design-partner stage <select className="input" value={item.design_partner_stage || 'discovery'} onChange={(event) => void submit(`/me/consulting/engagements/${item.id}`, { design_partner_stage: event.target.value }, 'Vaettir partner stage updated.', 'PATCH')}><option value="discovery">Discovery</option><option value="proposed">Proposed</option><option value="active">Active</option><option value="completed">Completed</option><option value="declined">Declined</option></select></label></>}</article>)}{!loading && workspace.engagements.length === 0 && <article className="card"><h3>No engagements yet</h3><p>Convert a won lead into delivery work, or record a Vaettir paid design partnership.</p></article>}</div></section>

    <section className="card" aria-labelledby="offer-heading"><span className="eyebrow">Entry offer</span><h2 id="offer-heading" style={{ marginTop: 14 }}>Turn your expertise into one clear first engagement.</h2><p>Define a small outcome a client can understand and buy: the problem, time frame, deliverables, and price. It might be a commissioned concept, menu consultation, sales audit, workshop, operational review, technical assessment, or another service grounded in your record.</p></section>
    <section className="card" aria-labelledby="search-consulting-heading"><span className="eyebrow">Kall lead finder</span><h2 id="search-consulting-heading" style={{ marginTop: 14 }}>Find and qualify consulting, fractional, advisory, and project work.</h2><p>Kall turns a professional direction into public searches, warm-network prompts, and questions that separate real opportunities from vague interest.</p><form className="form" onSubmit={(event) => void prepareLeadSearch(event)} style={{ marginTop: 20 }}><ProfessionalProfileSelect value={profileId} onChange={setProfileId} required /><label><span className="muted">Optional specialty, industry, or client problem</span><input className="input" value={extraTerms} onChange={(event) => setExtraTerms(event.target.value)} placeholder="Restaurant menu design, gallery commissions, regional sales training…" /></label><button className="button" type="submit">Find lead paths</button></form>{discoveryPlan && <div className={styles.results}>{discoveryPlan.results.length > 0 && <><h3>Open consulting work</h3><div className={styles.cardGrid}>{discoveryPlan.results.map((result) => <article className="card" key={result.url}><span className="pill">{result.provider}</span><h3 className={styles.cardTitle}>{result.title}</h3>{result.snippet && <p>{result.snippet}</p>}<div className={styles.actions}><a className="button secondary" href={result.url} target="_blank" rel="noreferrer">Open</a><button className="button ghost" type="button" onClick={() => chooseForm('lead')}>Track as a lead</button></div></article>)}</div></>}<h3>Your search brief</h3><p>{discoveryPlan.positioning}</p><h3>Qualify each lead</h3><ol>{discoveryPlan.qualification_questions.map((question) => <li key={question}>{question}</li>)}</ol>{discoveryPlan.warm_lead_prompts.length > 0 && <><h3>Start with people you know</h3>{discoveryPlan.warm_lead_prompts.map((prompt) => <article className="card" key={prompt.contact_id}><strong>{prompt.name}{prompt.company ? ` · ${prompt.company}` : ''}</strong><p>{prompt.assistant_prompt}</p></article>)}</>}</div>}<div className={styles.channels}>{CHANNELS.map((channel) => <a key={channel.name} href={channel.url} target="_blank" rel="noreferrer"><strong>{channel.name}</strong><span>{channel.note}</span></a>)}</div>{queries.length > 0 && <div className={styles.results}><GoogleJobSearchResults queries={queries} profileId={profileId || undefined} mode="consulting" /></div>}</section>
    <p className="notice">Consulting records are private to your account. Kall does not scrape private networks, send outreach, submit proposals, or claim a client relationship.</p>
  </section>;
}

function Editor({ form, leads, selectedLeadId, setSelectedLeadId, submit, close }: { form: 'lead' | 'proposal' | 'follow-up' | 'engagement'; leads: Lead[]; selectedLeadId: string; setSelectedLeadId: (value: string) => void; submit: Submit; close: () => void }) {
  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); let path = '/me/consulting/leads'; let body: Record<string, unknown> = {};
    if (form === 'lead') body = { organization: data.get('organization'), opportunity_name: data.get('opportunity_name'), relationship_segment: data.get('relationship_segment'), service_line: data.get('service_line') || null, source: data.get('source') || null, projected_value_cents: data.get('projected_value') ? Number(data.get('projected_value')) * 100 : null, next_step: data.get('next_step') || null };
    if (form === 'proposal') { path = '/me/consulting/proposals'; body = { lead_id: Number(data.get('lead_id')), title: data.get('title'), summary: data.get('summary') || null, scope: data.get('scope') || null, deliverables: String(data.get('deliverables') || '').split('\n').map((item) => item.trim()).filter(Boolean), fee_cents: data.get('fee') ? Number(data.get('fee')) * 100 : null }; }
    if (form === 'follow-up') { path = '/me/consulting/follow-ups'; body = { lead_id: Number(data.get('lead_id')), due_on: data.get('due_on'), channel: data.get('channel'), purpose: data.get('purpose'), draft_message: data.get('draft_message') || null }; }
    if (form === 'engagement') { path = '/me/consulting/engagements'; const vaettir = data.get('vaettir') === 'on'; body = { lead_id: data.get('lead_id') ? Number(data.get('lead_id')) : null, client_name: data.get('client_name'), name: data.get('name'), status: data.get('status'), fee_cents: data.get('fee') ? Number(data.get('fee')) * 100 : null, design_partner_product: vaettir ? 'vaettir' : null, design_partner_stage: vaettir ? data.get('design_partner_stage') : null }; }
    if (await submit(path, body, `${form === 'follow-up' ? 'Follow-up' : form[0].toUpperCase() + form.slice(1)} saved.`)) close();
  }
  return <section id="consulting-editor" className={`card ${styles.editor}`} aria-labelledby="consulting-editor-heading"><div className={styles.cardTop}><div><span className="eyebrow">New {form}</span><h2 id="consulting-editor-heading">{form === 'lead' ? 'Capture a real opportunity.' : form === 'proposal' ? 'Prepare a proposal draft.' : form === 'follow-up' ? 'Queue one reviewable message.' : 'Track delivery work.'}</h2></div><button className="button ghost" type="button" onClick={close}>Close</button></div><form className="form" onSubmit={onSubmit}>
    {form !== 'lead' && <label><span className="muted">Lead {form === 'engagement' && '(optional)'}</span><select className="input" name="lead_id" required={form !== 'engagement'} value={selectedLeadId} onChange={(event) => setSelectedLeadId(event.target.value)}><option value="">{form === 'engagement' ? 'No linked lead' : 'Select a lead'}</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.organization}: {lead.opportunity_name}</option>)}</select></label>}
    {form === 'lead' && <><div className="two"><label><span className="muted">Organization</span><input className="input" name="organization" required /></label><label><span className="muted">Opportunity</span><input className="input" name="opportunity_name" required /></label></div><div className="two"><label><span className="muted">Relationship</span><select className="input" name="relationship_segment">{SEGMENTS.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label><span className="muted">Service line</span><input className="input" name="service_line" placeholder="Release readiness" /></label></div><div className="two"><label><span className="muted">Source</span><input className="input" name="source" placeholder="Referral, Catalant, conference" /></label><label><span className="muted">Estimated value (USD)</span><input className="input" name="projected_value" type="number" min="0" step="1" /></label></div><label><span className="muted">Next step</span><input className="input" name="next_step" placeholder="Confirm a 30-minute discovery call" /></label></>}
    {form === 'proposal' && <><label><span className="muted">Proposal title</span><input className="input" name="title" required defaultValue="Release Readiness and Quality Risk Assessment" /></label><label><span className="muted">Executive summary</span><textarea className={styles.textarea} name="summary" rows={3} /></label><label><span className="muted">Scope</span><textarea className={styles.textarea} name="scope" rows={4} /></label><label><span className="muted">Deliverables, one per line</span><textarea className={styles.textarea} name="deliverables" rows={4} defaultValue={'Executive risk brief\nPrioritized remediation plan\nLeadership review'} /></label><label><span className="muted">Fee (USD)</span><input className="input" name="fee" type="number" min="0" step="1" defaultValue="5000" /></label></>}
    {form === 'follow-up' && <><div className="two"><label><span className="muted">Due date</span><input className="input" name="due_on" type="date" required /></label><label><span className="muted">Channel</span><select className="input" name="channel"><option value="email">Email</option><option value="phone">Phone</option><option value="linkedin">LinkedIn</option><option value="meeting">Meeting</option><option value="other">Other</option></select></label></div><label><span className="muted">Purpose</span><input className="input" name="purpose" required placeholder="Share the assessment outline" /></label><label><span className="muted">Message draft</span><textarea className={styles.textarea} name="draft_message" rows={5} /></label><p className={styles.boundary}>Saving creates a private draft. It does not send the message.</p></>}
    {form === 'engagement' && <><div className="two"><label><span className="muted">Client</span><input className="input" name="client_name" required /></label><label><span className="muted">Engagement</span><input className="input" name="name" required /></label></div><div className="two"><label><span className="muted">Status</span><select className="input" name="status"><option value="planned">Planned</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label><span className="muted">Fee (USD)</span><input className="input" name="fee" type="number" min="0" step="1" /></label></div><label className={styles.check}><input name="vaettir" type="checkbox" /> This is a paid Vaettir design partnership</label><label><span className="muted">Vaettir partner stage</span><select className="input" name="design_partner_stage" defaultValue="discovery"><option value="discovery">Discovery</option><option value="proposed">Proposed</option><option value="active">Active</option><option value="completed">Completed</option><option value="declined">Declined</option></select></label></>}
    <div className={styles.actions}><button className="button" type="submit">Save {form}</button><button className="button ghost" type="button" onClick={close}>Cancel</button></div></form></section>;
}

function ProposalCard({ item, leadName, submit }: { item: Proposal; leadName?: string; submit: Submit }) {
  const [editing, setEditing] = useState(false);
  return <article className="card"><div className={styles.cardTop}><span className="pill">{label(item.status)}</span><span className={styles.value}>{money(item.fee_cents)}</span></div><h3 className={styles.cardTitle}>{item.title}</h3><p>{leadName || 'Consulting lead'}</p>{item.summary && <p className={styles.nextStep}>{item.summary}</p>}{editing ? <form className="form" onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (await submit(`/me/consulting/proposals/${item.id}`, { summary: data.get('summary'), scope: data.get('scope'), deliverables: String(data.get('deliverables') || '').split('\n').map((value) => value.trim()).filter(Boolean), fee_cents: data.get('fee') ? Number(data.get('fee')) * 100 : null }, 'Proposal draft updated. Review approval was reset.', 'PATCH')) setEditing(false); }}><label><span className="muted">Summary</span><textarea className={styles.textarea} name="summary" rows={3} defaultValue={item.summary || ''} /></label><label><span className="muted">Scope</span><textarea className={styles.textarea} name="scope" rows={4} defaultValue={item.scope || ''} /></label><label><span className="muted">Deliverables</span><textarea className={styles.textarea} name="deliverables" rows={3} defaultValue={item.deliverables.join('\n')} /></label><label><span className="muted">Fee (USD)</span><input className="input" name="fee" type="number" min="0" defaultValue={item.fee_cents === null ? '' : item.fee_cents / 100} /></label><div className={styles.actions}><button className="button" type="submit">Save changes</button><button className="button ghost" type="button" onClick={() => setEditing(false)}>Cancel</button></div></form> : <div className={styles.actions}><button className="button secondary" type="button" onClick={() => setEditing(true)}>Edit draft</button>{item.status !== 'approved_for_manual_use' && <button className="button" type="button" onClick={() => void submit(`/me/consulting/proposals/${item.id}/approve`, { confirm_reviewed_for_manual_use: true }, 'Proposal approved for manual use.')}>Approve for manual use</button>}</div>}<p className={styles.boundary}>Kall cannot send or submit this proposal.</p></article>;
}

function FollowUpCard({ item, leadName, submit }: { item: FollowUp; leadName?: string; submit: Submit }) {
  const [draft, setDraft] = useState(item.draft_message || '');
  const dirty = draft !== (item.draft_message || '');
  return <article className="card"><div className={styles.cardTop}><span className="pill">{label(item.status)}</span><time dateTime={item.due_on}>{new Date(`${item.due_on}T12:00:00`).toLocaleDateString()}</time></div><h3 className={styles.cardTitle}>{item.purpose}</h3><p>{leadName || 'Consulting lead'} · {label(item.channel)}</p>{item.status !== 'completed' && <><label className={styles.draftLabel}><span className="muted">Message draft</span><textarea className={styles.textarea} rows={5} value={draft} onChange={(event) => setDraft(event.target.value)} /></label><div className={styles.actions}><button className="button secondary" type="button" disabled={!dirty} onClick={() => void submit(`/me/consulting/follow-ups/${item.id}`, { draft_message: draft }, 'Follow-up draft saved. Review approval was reset.', 'PATCH')}>Save draft</button>{item.status !== 'approved_for_manual_use' ? <button className="button" type="button" disabled={dirty || !draft.trim()} onClick={() => void submit(`/me/consulting/follow-ups/${item.id}/approve`, { confirm_reviewed_for_manual_use: true }, 'Follow-up approved for manual use.')}>Approve for manual use</button> : <button className="button" type="button" disabled={dirty} onClick={() => void submit(`/me/consulting/follow-ups/${item.id}/complete`, { confirm_completed_outside_kall: true }, 'Follow-up recorded as completed outside Kall.')}>I completed this outside Kall</button>}</div>{dirty && <p className={styles.boundary}>Save this version before approving it.</p>}</>}<p className={styles.boundary}>Approval records your review. Sending still happens outside Kall.</p></article>;
}
