/* Design study only. No API calls, user data, analytics or application submission. */
const query = new URLSearchParams(location.search);
const themes = ['edition', 'vector', 'horizon', 'current'];
const pages = ['brief', 'opportunities', 'career', 'review'];
const theme = themes.includes(query.get('theme')) ? query.get('theme') : 'edition';
const screen = pages.includes(query.get('screen')) ? query.get('screen') : 'brief';
document.body.dataset.theme = theme;
document.body.dataset.screen = screen;
document.title = `Kall ${theme} | ${screen} | Unapproved design study`;
const paths = {brief:'M4 5h16v14H4z M8 9h8 M8 13h5', opportunities:'M10 4a6 6 0 1 0 0 12a6 6 0 0 0 0-12 M15 15l5 5', career:'M12 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8 M4 21v-3a8 8 0 0 1 16 0v3', applications:'M8 6V3h8v3 M3 6h18v15H3z M3 11h18 M10 11v3h4v-3', documents:'M6 2h8l5 5v15H6z M14 2v6h5 M9 12h7 M9 16h7', arrow:'M4 12h15 M14 7l5 5-5 5', check:'M5 12l4 4L19 6', lock:'M6 10h12v11H6z M8 10V7a4 4 0 1 1 8 0v3', plus:'M12 4v16 M4 12h16', down:'M6 9l6 6 6-6'};
const icon = (name) => `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name] || paths.brief}"/></svg>`;
const preview = (p) => `mockup.html?theme=${theme}&screen=${p}`;
const link = (label, p, cls='') => `<a class="${cls}" href="${preview(p)}">${label}</a>`;
const button = (text, secondary=false) => `<button class="button ${secondary?'secondary':''}" type="button" data-demo>${text}</button>`;
const pill = (text, cls='') => `<span class="pill ${cls}">${text}</span>`;
const mark = theme === 'current' ? '<img src="assets/current-bindrune.svg" alt="" width="28" height="28">' : `<span class="lettermark" aria-hidden="true">${theme === 'vector'?'K':'k'}</span>`;
const nav = [['brief','Brief'],['opportunities','Opportunities'],['applications','Applications'],['documents','Documents'],['career','Career']];
const active = screen === 'review' ? 'applications' : screen;
const navlinks = nav.map(([key,label])=>`<a href="${key==='documents'?'#':preview(key==='applications'?'review':key)}" ${key==='documents'?'data-demo':''} ${key===active?'aria-current="page"':''}>${icon(key)}<span>${label}</span>${key==='applications'?'<b class="nav-count">1</b>':''}</a>`).join('');
const shell = (content) => `
  <div class="study-band"><span>UNAPPROVED CONCEPT / ${theme.toUpperCase()}</span><span>Fictional data · Local preview</span></div>
  <div class="workspace">
  <aside class="sidebar">
    <a class="wordmark" href="${preview('brief')}" aria-label="Kall Brief">${mark}<span>${theme==='vector'?'Kall':'kall'}</span></a>
    <nav aria-label="Primary">${navlinks}</nav>
    <div class="sidebar-note">${icon('lock')}<span>Your career.<br>Your control.</span></div>
    <div class="account"><span class="avatar">AM</span><div><b>Alex Morgan</b><small>Personal workspace</small></div>${icon('down')}</div>
  </aside>
  <div class="main-wrap"><header class="topbar"><span class="location">Workspace <i>/</i> ${screen==='review'?'Application review':screen.charAt(0).toUpperCase()+screen.slice(1)}</span><div class="top-actions"><span class="privacy">${icon('lock')} Private workspace</span><span class="avatar">AM</span></div></header>
  <main id="content">${content}</main><footer class="screen-footer"><span>Kall / Your next move, with intention.</span><span>Design study · Not a live application</span></footer></div></div>
  <nav class="mobile-nav" aria-label="Mobile primary">${navlinks}</nav>`;
const heading = (eyebrow,title,subtitle,action='')=>`<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lede">${subtitle}</p></div>${action}</div>`;
const company = (name='Northstar Labs', short='N')=>`<span class="company-mark">${short}</span><span>${name}<small>Product infrastructure</small></span>`;
const traits = ()=>`<div class="traits">${pill('Remote')}${pill('United States')}${pill('$170k–$205k base')}</div>`;
const evidence = ()=>`<div class="evidence"><div><span class="mini-check">${icon('check')}</span><p><b>Leadership at the right scale</b><small>Your record includes leading a 12-person quality team.</small></p></div><div><span class="mini-check">${icon('check')}</span><p><b>A functional-area match · +10 points</b><small>Quality Engineering aligns with your strategy. One bonus, capped at 10 points.</small></p></div><div><span class="mini-gap">!</span><p><b>One detail to explore</b><small>The posting asks for hands-on payments experience.</small></p></div></div>`;
const jobRow=(name,org,score,short,last=false)=>`<div class="job-row ${last?'last':''}"><span class="company-mark">${short}</span><div class="job-copy"><h3>${name}</h3><p>${org} · Remote</p></div><span class="match-small">${score}% <small>fit</small></span><a aria-label="Review ${name}" href="${preview('opportunities')}">${icon('arrow')}</a></div>`;
function brief(){ return heading('MONDAY, 31 AUGUST · YOUR BRIEF','Your next move, in focus.','A few useful things. A clear place to begin.',link('Search for a job '+icon('arrow'),'opportunities','button secondary'))+`
  <section class="hero-grid"><article class="focus-card"><div class="focus-top"><p class="eyebrow">WORTH YOUR ATTENTION</p>${pill('New opportunity','accent')}</div><div class="company-line">${company()}</div><h2>Director, Quality<br class="desktop-only"> Engineering</h2>${traits()}<p class="focus-description">A strong match for how you lead teams and build quality into the way products ship.</p><div class="focus-action">${link('Review opportunity '+icon('arrow'),'opportunities','button')}<span class="match"><strong>92<span>%</span></strong><small>Evidence-based fit</small></span></div><div class="fineprint">Fit is a helpful signal, not a prediction of an offer.</div></article>
  <aside class="day-note"><div class="material-art" aria-hidden="true"><img src="art/${theme==='current'?'edition':theme}-board.png" alt=""></div><div class="note-copy"><p class="eyebrow">ROOM TO THINK</p><h2>Progress can <br>be one good <br>conversation.</h2><p>Keep your next step small.<br>Make it a meaningful one.</p><span class="tiny-rule"></span></div></aside></section>
  <div class="lower-grid"><section class="panel"><div class="section-title"><h2>New in your search <span>3</span></h2>${link('See all','opportunities')}</div>${jobRow('Head of Quality','Signal Works',87,'S')}${jobRow('Quality Engineering Lead','Fieldnote',84,'F',true)}</section><aside class="panel next-step"><p class="eyebrow">READY WHEN YOU ARE</p><h2>One application<br>needs your review.</h2><p>Your tailored resume is ready. Check the facts before approving.</p>${link('Open review '+icon('arrow'),'review','text-link')}<div class="quiet-status"><span class="status-dot"></span>Monitoring checked at 09:10<span>3 boards</span></div></aside></div>`; }
function opportunities(){ return heading('OPPORTUNITIES','Find work that fits.','Your strategy, translated into possibilities.',button('Edit search',true))+`
  <div class="search-bar"><span>${icon('opportunities')}</span><b>Quality Engineering leadership</b><span class="search-divider"></span><span>Remote · United States</span>${icon('down')}</div>
  <div class="filterbar"><div class="tab-links"><b>For you <span>3</span></b><span>Saved <span>8</span></span><span>Monitoring</span></div><span class="quiet-label"><span class="status-dot"></span>Checked 09:10</span></div>
  <div class="opportunity-grid"><section class="job-list" aria-label="Opportunity list">
    <article class="job-card selected"><div class="job-card-head"><span class="company-mark">N</span>${pill('92% fit','accent')}</div><h2>Director, Quality Engineering</h2><p>Northstar Labs</p><div class="job-meta">Remote · United States<br>$170k–$205k base</div><div class="job-card-foot"><span>Added today</span><b>Selected ${icon('arrow')}</b></div></article>
    <article class="job-card"><div class="job-card-head"><span class="company-mark">S</span>${pill('87% fit')}</div><h2>Head of Quality</h2><p>Signal Works</p><div class="job-meta">Remote · United States<br>$165k–$195k base</div><div class="job-card-foot"><span>Added today</span><span>View details</span></div></article>
    <article class="job-card"><div class="job-card-head"><span class="company-mark">F</span>${pill('84% fit')}</div><h2>Quality Engineering Lead</h2><p>Fieldnote</p><div class="job-meta">Remote · United States<br>$150k–$180k base</div></article>
  </section><article class="panel job-detail"><div class="company-line">${company()}</div><h2>Director, Quality Engineering</h2>${traits()}<div class="detail-actions">${link('Prepare application '+icon('arrow'),'review','button')}${button('Save',true)}</div><div class="section-title intelligence-title"><h3>Why this could fit</h3><span>Job Intelligence</span></div>${evidence()}<div class="posting-excerpt"><p class="eyebrow">FROM THE POSTING</p><p>Build a quality engineering practice that partners with product teams from discovery through release. Coach leaders, improve test strategy, and make reliability a shared responsibility.</p><small>Fictional example · Verify details with the employer.</small></div><a class="text-link" href="${preview('career')}">Adjust your career strategy ${icon('arrow')}</a></article></div>`; }
function career(){ return heading('CAREER','A direction that is yours.','Define the work you want. Keep the full story behind it.',button('New strategy '+icon('plus'),true))+`
  <div class="career-tabs"><b>Strategy</b><span>Work history</span><span>Professional record</span><span>Growth</span><span>References</span></div>
  <div class="career-grid"><section class="panel strategy"><div class="section-title"><div><p class="eyebrow">ACTIVE STRATEGY</p><h2>Quality Engineering leadership</h2></div>${pill('Active','accent')}</div><p class="strategy-intro">Lead thoughtful teams. Build confidence into complex products.</p>
  <div class="field-group"><span class="field-label">Target roles</span><div class="field-value">Director of Quality Engineering<br>Head of Quality · Quality Engineering Lead</div></div>
  <div class="field-group"><span class="field-label">Functional areas</span><div class="field-value tags">${pill('Quality Engineering')}${pill('Engineering Leadership')}</div><small>Related roles can appear too. Your exclusions still apply.</small></div>
  <div class="field-pair"><div class="field-group"><span class="field-label">Location & work style</span><div class="field-value">United States · Remote</div></div><div class="field-group"><span class="field-label">Target base salary</span><div class="field-value">$175,000</div></div></div>
  <div class="field-group"><span class="field-label">Exclude keywords</span><div class="field-value">Commission only, unpaid internship</div></div>
  <div class="strategy-actions">${button('Edit strategy '+icon('arrow'))}${button('Pause search',true)}</div></section>
  <aside class="career-side"><section class="panel resume-card"><p class="eyebrow">DEFAULT RESUME</p><div class="document-object"><span>AM</span><b>Alex Morgan</b><small>QUALITY ENGINEERING LEADER</small><i></i><i></i><i></i><i></i></div><h3>Leadership resume</h3><p>Version 4 · Updated 28 Aug</p>${button('Review resume',true)}</section><section class="panel growth-card"><p class="eyebrow">GROWTH</p><h2>Build toward <br>what comes next.</h2><p>Explore a development plan for your next career chapter.</p><a class="text-link" href="${preview('career')}">Explore growth ${icon('arrow')}</a></section></aside></div>`; }
function review(){ return heading('APPLICATIONS / NEEDS REVIEW','Make it yours before it goes.','Review the evidence, confirm the facts, then choose what happens next.',pill('Not submitted','accent'))+`
  <div class="review-stepper"><span class="done">${icon('check')} Prepare</span><i></i><b><em>2</em> Review</b><i></i><span><em>3</em> Approve</span><i></i><span><em>4</em> Submit</span></div>
  <div class="review-grid"><article class="panel review-document"><div class="section-title"><h2>Tailored resume</h2><span>Version 4 · PDF preview</span></div><div class="paper-resume"><div class="resume-header"><h2>Alex Morgan</h2><p>QUALITY ENGINEERING LEADER</p><small>United States · Open to remote roles</small></div><h3>PROFILE</h3><p>Quality engineering leader building confident teams and dependable products. Connects test strategy, delivery practices, and customer outcomes.</p><h3>SELECTED EXPERIENCE</h3><div class="resume-role"><b>Quality Engineering Manager</b><span>2021–2026</span></div><p>Example Company</p><ul><li>Led a 12-person quality team across three product groups.</li><li>Introduced risk-based release reviews and clear ownership of test strategy.</li><li>Partnered with engineering and product leaders on reliability goals.</li></ul><h3>CORE STRENGTHS</h3><p>Quality strategy · Team leadership · Test automation<br>Release confidence · Cross-functional collaboration</p><div class="resume-highlight">${icon('check')} Uses your recorded experience. No qualifications added.</div></div></article>
  <aside class="review-side"><section class="panel"><p class="eyebrow">APPLICATION FOR</p><h2>Director, Quality Engineering</h2><p>Northstar Labs · Remote</p><div class="review-checks"><div>${icon('check')} Resume facts reviewed</div><div>${icon('check')} Contact details reviewed</div><div><span class="circle-empty"></span> Confirm sensitive fields</div></div><div class="safety-note">${icon('lock')}<div><b>You stay in control.</b><p>EEO and work authorization answers need your explicit confirmation. Nothing is submitted automatically.</p></div></div><button class="button disabled" disabled>Approve preparation ${icon('arrow')}</button><p class="fineprint">Approval unlocks after all required confirmations. Submission is a separate action.</p>${button('Save and come back',true)}</section><div class="review-help"><span>Need a change?</span><a href="${preview('career')}">Edit your source profile ${icon('arrow')}</a></div></aside></div>`; }
document.getElementById('app').innerHTML=shell(({brief,opportunities,career,review})[screen]());
document.addEventListener('click',event=>{if(event.target.closest('[data-demo]')){event.preventDefault();const toast=document.getElementById('toast');toast.textContent='Design preview only. No changes were saved.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000);}});
