name: Build Android (production)

on:
  push:
    branches: ['main']
    paths: ['apps/mobile/**']

jobs:
  build_android:
    defaults:
      run:
        working_directory: apps/mobile
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run: eas build --platform android --profile android-production --non-interactive --no-wait
