name: Build Android (production)

on:
  push:
    branches: ['main']
    paths: ['apps/mobile/**']

jobs:
  build_android:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
        working_directory: apps/mobile
      - run: npx eas-cli build --platform android --profile android-production --non-interactive --no-wait
        working_directory: apps/mobile
